name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: make install

      - name: Cython
        run: make cython

      - name: Lint
        run: make lint

      - name: Run tests
        run: make test
